// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"_Tona_Core","status":true,"description":"","parameters":{}},
{"name":"_Tona_Data","status":true,"description":"","parameters":{}},
{"name":"_Tona_Actor","status":true,"description":"","parameters":{}},
{"name":"_Tona_Quest","status":true,"description":"","parameters":{}},
{"name":"_Tona_Window","status":true,"description":"","parameters":{}},
{"name":"_Tona_Command","status":true,"description":"","parameters":{}},
{"name":"_Tona_Lobby","status":true,"description":"","parameters":{}},
{"name":"_Tona_Main","status":true,"description":"","parameters":{}}
];
